/* Generated By:JavaCC: Do not edit this line. RobotConstants.java */
package uniandes.lym.robot.control;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RobotConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ARM = 5;
  /** RegularExpression Id. */
  int MOVE = 6;
  /** RegularExpression Id. */
  int FSKIP = 7;
  /** RegularExpression Id. */
  int PUT = 8;
  /** RegularExpression Id. */
  int PICK = 9;
  /** RegularExpression Id. */
  int TURN = 10;
  /** RegularExpression Id. */
  int FACE = 11;
  /** RegularExpression Id. */
  int MOVE_DIR = 12;
  /** RegularExpression Id. */
  int RUN_DIRS = 13;
  /** RegularExpression Id. */
  int MOVE_FACE = 14;
  /** RegularExpression Id. */
  int NULL = 15;
  /** RegularExpression Id. */
  int IF = 16;
  /** RegularExpression Id. */
  int WHILE = 17;
  /** RegularExpression Id. */
  int FOR = 18;
  /** RegularExpression Id. */
  int DEFVAR = 19;
  /** RegularExpression Id. */
  int EQUALS = 20;
  /** RegularExpression Id. */
  int DEFUN = 21;
  /** RegularExpression Id. */
  int LEFT = 22;
  /** RegularExpression Id. */
  int RIGHT = 23;
  /** RegularExpression Id. */
  int AROUND = 24;
  /** RegularExpression Id. */
  int BACK = 25;
  /** RegularExpression Id. */
  int FRONT = 26;
  /** RegularExpression Id. */
  int NORTH = 27;
  /** RegularExpression Id. */
  int SOUTH = 28;
  /** RegularExpression Id. */
  int EAST = 29;
  /** RegularExpression Id. */
  int WEST = 30;
  /** RegularExpression Id. */
  int X_OBJECT = 31;
  /** RegularExpression Id. */
  int FACING = 32;
  /** RegularExpression Id. */
  int BLOCKED = 33;
  /** RegularExpression Id. */
  int CAN_PUT = 34;
  /** RegularExpression Id. */
  int CAN_PICK = 35;
  /** RegularExpression Id. */
  int CAN_MOVE = 36;
  /** RegularExpression Id. */
  int IS_ZERO = 37;
  /** RegularExpression Id. */
  int NOT = 38;
  /** RegularExpression Id. */
  int DIM = 39;
  /** RegularExpression Id. */
  int MY_X_POS = 40;
  /** RegularExpression Id. */
  int MY_Y_POS = 41;
  /** RegularExpression Id. */
  int MY_CHIPS = 42;
  /** RegularExpression Id. */
  int MY_BALLOONS = 43;
  /** RegularExpression Id. */
  int BALLOONS_HERE = 44;
  /** RegularExpression Id. */
  int CHIPS_HERE = 45;
  /** RegularExpression Id. */
  int SPACES = 46;
  /** RegularExpression Id. */
  int IDENTIFIER = 47;
  /** RegularExpression Id. */
  int NUM = 48;
  /** RegularExpression Id. */
  int LETTER = 49;
  /** RegularExpression Id. */
  int DIGIT = 50;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"(\"",
    "\"move\"",
    "\"skip\"",
    "\"put\"",
    "\"pick\"",
    "\"turn\"",
    "\"face\"",
    "\"move-dir\"",
    "\"run-dirs\"",
    "\"move-face\"",
    "\"null\"",
    "\"if\"",
    "\"loop\"",
    "\"repeat\"",
    "\"defvar\"",
    "\"=\"",
    "\"defun\"",
    "\":left\"",
    "\":right\"",
    "\":around\"",
    "\":back\"",
    "\":front\"",
    "\":north\"",
    "\":south\"",
    "\":east\"",
    "\":west\"",
    "<X_OBJECT>",
    "\"facing?\"",
    "\"blocked?\"",
    "\"can-put?\"",
    "\"can-pick?\"",
    "\"can-move?\"",
    "\"isZero?\"",
    "\"not\"",
    "\"dim\"",
    "\"myXpos\"",
    "\"myYpos\"",
    "\"myChips\"",
    "\"myBalloons\"",
    "\"balloonsHere\"",
    "\"chipsHere\"",
    "\"spaces\"",
    "<IDENTIFIER>",
    "<NUM>",
    "<LETTER>",
    "<DIGIT>",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
  };

}
